//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westwind.Web.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Westwind.Web.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap output returned must specify a Content type. For example: [CallbackMethod(ContentType=&quot;image/png&quot;)].
        /// </summary>
        internal static string BitmapOutputReturnedMustSpecifyAContentType {
            get {
                return ResourceManager.GetString("BitmapOutputReturnedMustSpecifyAContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get values if AllowUpdates is not set to true.
        /// </summary>
        internal static string CanTGetValuesIfAllowUpdatesIsNotSetToTrue {
            get {
                return ResourceManager.GetString("CanTGetValuesIfAllowUpdatesIsNotSetToTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to call a Wcf or ASMX service you have to specify ClientProxyTargetType of the Web Service instance..
        /// </summary>
        internal static string ERROR_CLASSWRAPPER_FORWCFASMX_REQUIRES_CLIENTPROXYTYPE {
            get {
                return ResourceManager.GetString("ERROR_CLASSWRAPPER_FORWCFASMX_REQUIRES_CLIENTPROXYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON string input..
        /// </summary>
        internal static string ERROR_INVALID_JSON_STRING {
            get {
                return ResourceManager.GetString("ERROR_INVALID_JSON_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one ScriptContainer is allowed per page..
        /// </summary>
        internal static string ERROR_ONLYONE_SCRIPTCONTAINER_PER_PAGE_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_ONLYONE_SCRIPTCONTAINER_PER_PAGE_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptContainer.Current only works with Page based handlers..
        /// </summary>
        internal static string ERROR_ScriptContainer_OnlyWorks_With_PageBasedHandlers {
            get {
                return ResourceManager.GetString("ERROR_ScriptContainer_OnlyWorks_With_PageBasedHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert content type {0} to ImageFormat.
        /// </summary>
        internal static string ERROR_UnableToConvertContentTypeToImageFormat {
            get {
                return ResourceManager.GetString("ERROR_UnableToConvertContentTypeToImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert ImageFormat {0} to ContentType.
        /// </summary>
        internal static string ERROR_UnableToConvertImageFormatToContentType {
            get {
                return ResourceManager.GetString("ERROR_UnableToConvertImageFormatToContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BindingSource.
        /// </summary>
        internal static string InvalidBindingSource {
            get {
                return ResourceManager.GetString("InvalidBindingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Control.
        /// </summary>
        internal static string InvalidControl {
            get {
                return ResourceManager.GetString("InvalidControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Control Id.
        /// </summary>
        internal static string InvalidControlId {
            get {
                return ResourceManager.GetString("InvalidControlId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Server Method..
        /// </summary>
        internal static string InvalidServerMethod {
            get {
                return ResourceManager.GetString("InvalidServerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL: Virtual path relative URL (~) not allowed when HttpContext not available..
        /// </summary>
        internal static string InvalidURLRelativeURLNotAllowed {
            get {
                return ResourceManager.GetString("InvalidURLRelativeURLNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed. Method expects {0}..
        /// </summary>
        internal static string NotAllowedMethodExpectsVerb {
            get {
                return ResourceManager.GetString("NotAllowedMethodExpectsVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server method is not accessible due to missing CallbackMethod attribute.
        /// </summary>
        internal static string ServerMethodIsNotAccessibleDueToMissing {
            get {
                return ResourceManager.GetString("ServerMethodIsNotAccessibleDueToMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported JSON Serializer specified. Json.Net and System.Web.Extensions must be explicitly compiled in..
        /// </summary>
        internal static string UnsupportedJSONSerializerSpecified {
            get {
                return ResourceManager.GetString("UnsupportedJSONSerializerSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebResource not available for jQuery UI.
        /// </summary>
        internal static string WebResourceNotAvailableForJQueryUI {
            get {
                return ResourceManager.GetString("WebResourceNotAvailableForJQueryUI", resourceCulture);
            }
        }
    }
}
