//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westwind.Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Westwind.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection string must be passed to the constructor.
        /// </summary>
        public static string AConnectionStringMustBePassedToTheConstructor {
            get {
                return ResourceManager.GetString("AConnectionStringMustBePassedToTheConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in your Application.
        /// </summary>
        public static string An_error_occurred_in_your_Application {
            get {
                return ResourceManager.GetString("An_error_occurred_in_your_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte[] value greater than 20megs are not supported.
        /// </summary>
        public static string ByteValueGreaterThan20megsAreNotSupported {
            get {
                return ResourceManager.GetString("ByteValueGreaterThan20megsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Configuration method is no longer supported. Use a Provider configuration instead..
        /// </summary>
        public static string ConfigurationMethodNoLongerSupported {
            get {
                return ResourceManager.GetString("ConfigurationMethodNoLongerSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader passed to DataReaderToObject cannot be closed.
        /// </summary>
        public static string DataReaderPassedToDataReaderToObjectCannot {
            get {
                return ResourceManager.GetString("DataReaderPassedToDataReaderToObjectCannot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Connection String..
        /// </summary>
        public static string InvalidConnectionString {
            get {
                return ResourceManager.GetString("InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Connection string name..
        /// </summary>
        public static string InvalidConnectionStringName {
            get {
                return ResourceManager.GetString("InvalidConnectionStringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex digit: .
        /// </summary>
        public static string InvalidHexDigit {
            get {
                return ResourceManager.GetString("InvalidHexDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex string length: {0}.
        /// </summary>
        public static string InvalidHexStringLength {
            get {
                return ResourceManager.GetString("InvalidHexStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type for XmlType to .NET Type conversion..
        /// </summary>
        public static string InvalidTypeForXmlTypeToNETTypeConversion {
            get {
                return ResourceManager.GetString("InvalidTypeForXmlTypeToNETTypeConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object could not be deserialized from Xml..
        /// </summary>
        public static string ObjectCouldNotBeDeserializedFromXml {
            get {
                return ResourceManager.GetString("ObjectCouldNotBeDeserializedFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Conversion not handled in StringToTypedValue for .
        /// </summary>
        public static string StringToTypedValueValueTypeConversionFailed {
            get {
                return ResourceManager.GetString("StringToTypedValueValueTypeConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read configuration string from Sql Server field..
        /// </summary>
        public static string UnableToExtractKeys {
            get {
                return ResourceManager.GetString("UnableToExtractKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read config information from string..
        /// </summary>
        public static string UnableToReadConfigDataFromString {
            get {
                return ResourceManager.GetString("UnableToReadConfigDataFromString", resourceCulture);
            }
        }
    }
}
